# --- Site basics ---
title: "Suraj Dighe — Data Engineering & AI"
description: "Event-driven data platforms on AWS, Databricks, Neo4j graphs, SQL tuning, and pragmatic GenAI."
url: "https://surajdtech.github.io"
baseurl: ""

# --- Theme ---
remote_theme: mmistakes/minimal-mistakes@4.26.2

# --- Plugins ---
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# --- Author (optional, safe defaults) ---
author:
  name: "Suraj Dighe"
  avatar: "/assets/img/profile.jpg"
  bio: "Senior QA & Data Engineer | AWS, Kinesis/MSK, Databricks, Neo4j | Performance & Cost Optimization"
  location: "Pune, IN"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/surajdtech"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/surajdtech"

# --- Content & layout ---
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/

collections:
  posts:
    output: true

# --- Defaults for posts ---
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
