# Site Basics
lang: en
title: "Suraj Dighe — Data Engineering & AI"
description: "Event-driven data platforms on AWS, Databricks, Neo4j graphs, SQL tuning, and pragmatic GenAI."
url: "https://surajdtech.github.io"
baseurl: ""


# Theme (Minimal Mistakes via remote_theme)
remote_theme: mmistakes/minimal-mistakes@4.26.2
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag


# Author
author:
name: "Suraj Dighe"
avatar: "/assets/img/profile.jpg" # optional: drop a photo here later
bio: "Senior QA & Data Engineer | AWS, Kinesis/MSK, Databricks, Neo4j | Performance & Cost Optimization"
location: "Pune, IN"
links:
- label: "GitHub"
icon: "fab fa-github"
url: "https://github.com/surajdtech"
- label: "LinkedIn"
icon: "fab fa-linkedin"
url: "https://www.linkedin.com/in/surajdtech"


# Navigation
collections:
posts:
output: true


# Minimal Mistakes Settings
minimal_mistakes_skin: "air"
search: true
permalink: /:categories/:title/


# SEO/Feed
feed:
path: feed.xml


# Markdown & Code
markdown: kramdown
highlighter: rouge


# Defaults
defaults:
- scope:
path: ""
type: posts
values:
layout: single
author_profile: true
read_time: true
comments: false
share: true
related: true
